pipeline {
    agent any

    stages {
        stage('Debug Environment') {
            steps {
                script {
                    sh 'whoami && groups && docker ps'
                }
            }
        }
        stage('Pull Docker Image') {
            steps {
                script {
                    sh 'docker pull hello-world'
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    sh 'docker run hello-world'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed!'
        }
    }
}
