# The Go binary
BINARY_NAME=app

# Default target to run tests
all: test

# Test target
test:
	@echo "Running tests..."
	go test ./ops/...

# Run target
run:
	@echo "Running the Go application..."
	go run main.go

# Clean target - Just runs the Go application
clean:
	@echo "Running the Go application..."
	go run main.go
